In [1]:
from preamble import*
%matplotlib inline

## 소개

## 왜 머신러닝인가?
* 머신러닝Machine Learning은 데이터에서 지식을 추출하는 작업
* 머신러닝은 통계학, 인공지능 그리고 컴퓨터 과학이 얽혀 있는 연구 분야
* 예측분석이나 통계적 머신러닝으로도 불립니다.

### NumPy

In [6]:
import numpy as np
x1 = np.array([1,2,3]) #1차원 배열
print("x1:\n",x1)
print(x1.shape)
print(x1.ndim)

x2 = np.array([[1,2,3],[4,5,6]]) #2차원 배열
print("x2:\n",x2)
print(x2.shape)
print(x2.ndim)

x1:
 [1 2 3]
(3,)
1
x2:
 [[1 2 3]
 [4 5 6]]
(2, 3)
2


### SciPy

In [8]:
A = np.zeros((2,2))
B = np.ones((2,2))
C = np.eye(2) #단위행렬

print(A)
print(B)
print(C)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]


In [9]:
from scipy import sparse

#대각선 원소는 1이고 나머지는 0인 2차원 NumPy배열을 만듭니다.
eye = np.eye(4)
print('NumPy 배열:\n', eye)

NumPy 배열:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# NumPy배열을 CSR 포맷의 SciPy희박행렬로 변환합니다.
#0이 아닌 원소만 저장됩니다. (1행1열, 2행2열, 3행3열 입니다)
sparse_matrix = sparse.csr_matrix(eye)
print("WnSciPy의 CSR 행렬:\n", sparse_matrix)

WnSciPy의 CSR 행렬:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [12]:
data = np.ones(4) 
data1 = np.ones((4,4)) #4행 4열을 1로 채워주세요
print(data)
print(data1)

row_indices = np.arange(4)
col_indicces = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indicces)))#coo:희소행렬과 동일하게 값나옴 
print("COO 표현:\n", eye_coo)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
COO 표현:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


### matplotlib

### pandas

### mglearn

## 이 책에서 사용하는 소프트웨어버전

In [15]:
import sys
print("Python 버전:", sys.version)

import pandas as pd
print("Pandas 버전:", pd.__version__)

import matplotlib
print("matplotlib버전:", matplotlib.__version__)

import numpy as np
print("NumPy버전:", np. __version__)

import scipy as sp
print("SciPy버전:", sp. __version__)

import IPython
print("IPython 버전:", IPython.__version__)

import sklearn
print("scikit-learn버전:", sklearn.__version__)

Python 버전: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Pandas 버전: 1.3.4
matplotlib버전: 3.4.3
NumPy버전: 1.20.3
SciPy버전: 1.7.1
IPython 버전: 7.29.0
scikit-learn버전: 0.24.2
